kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ${project.artifactId}
spec:
  template:
    metadata:
      labels:
        name: ${project.artifactId}
    spec:
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djava.net.preferIPv4Stack=true'
            - name: JAVA_ARGS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djava.net.preferIPv4Stack=true -cluster'
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: mongodb
                   key: database-user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: mongodb
                   key: database-password
            - name: DB_NAME
              valueFrom:
                 secretKeyRef:
                   name: mongodb
                   key: database-name        
            - name: REDIS_AUTH
              valueFrom:
                 secretKeyRef:
                   name: redis
                   key: database-password 
    replicas: 2
    minReplicas: 1 
    maxReplicas: 10 
    cpuUtilization:
      targetCPUUtilizationPercentage: 80     
  selector:
    name: ${project.artifactId}
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "vertx"
        from:
          kind: "ImageStreamTag"
          name: "deepsea-client:latest"